parameters:
  - name: architectures
    type: object
    default:
      - aarch64
      - amd64
      - amd64-cuda
      - jetson-nano
      - rpi3
  - name: image
    type: string

jobs:
  - strategy:
      matrix:
        ${{ each architecture in parameters.architectures }}:
          ${{ architecture }}:
            architecture: ${{ architecture }}
    template: build.yaml
    parameters:
      architecture: $(architecture)
      image: ${{ parameters.image }}
