trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viseronFFmpeg
      source: "Viseron FFmpeg"
      trigger:
        branches:
          - dev

stages:
- stage: OpenCV_Part_One
  jobs:
    - template: templates/build.yaml
      parameters:
        architectures:
          - jetson-nano
        image: opencvpartone
- stage: OpenCV
  dependsOn: OpenCV_Part_One
  jobs:
    - template: templates/build.yaml
      parameters:
        image: opencv
