trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viseronFFmpeg
      source: "Viseron FFmpeg"
      trigger:
        branches:
          - dev

jobs:
  - template: templates/build.yaml
    parameters:
      architectures:
        - jetson-nano
      image: opencv-part-one
  - template: templates/build.yaml
    parameters:
      image: opencv
